easy_admin:
  design:
    menu:
      - label: 'Gestion utilisateur'
        children:
          - entity: 'User'
            label: 'Utilisateurs'
            params: { sortField: 'username' }
            icon: 'user'
            default: true
          - entity: 'Role'
            label: 'Role'
            icon: 'user-tag'
            params: { sortField: 'Name' }