easy_admin:
  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - { property: 'Username'}
          - { property: 'Email' }
          - { property: 'Role' }

      form:
        fields:
          - {property: 'username', type: 'text', label: 'Nom utilisateur'}
          - {property: 'email', type: 'text', label: 'Email'}
          - { property: 'role', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Role' } }